accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:id>/follow/', views.follow, name='follow'),
    
]

movie_pjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('movies/', include('movies.urls')),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/',views.detail, name='detail'),
    path('<int:id>/scores/new/', views.score_create, name='score_create'),
    path('<int:movie_id>/scores/<int:score_id>/delete/', views.score_delete, name='score_delete'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="followers", blank=True)

movies/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.name
        
class Movie(models.Model):
    title = models.CharField(max_length=30)
    audience = models.IntegerField()
    poster_url = models.TextField()
    description = models.TextField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    
class Score(models.Model):
    content = models.CharField(max_length=100)
    value = models.IntegerField()
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCustomCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email',)

movies/forms.py
from django import forms
from .models import Score

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['content','value',]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .models import User

from .forms import UserCustomCreationForm

# Create your views here.
def list(request):
    users = User.objects.all()
    return render(request, 'accounts/list.html',{'users':users})

def detail(require,id):
    user_info = User.objects.get(id=id)
    return render(require, 'accounts/detail.html',{'user_info':user_info})
    
    
    
@require_http_methods(["GET", "POST"])
def signup(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        user_form = UserCustomCreationForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
            auth_login(request, user)
            return redirect('movies:list')
    else:
        user_form = UserCustomCreationForm()
    context = {'form': user_form}
    return render(request, 'accounts/forms.html', context)

def login(request):
    if request.user.is_authenticated:
        return redirect('movies:list')
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect('movies:list')
    else:
        login_form = AuthenticationForm()
    context = {'form': login_form}
    return render(request, 'accounts/forms.html', context)

@login_required
def logout(request):
    auth_logout(request)
    return redirect('movies:list')
    
def follow(request, id):
    me = request.user
    you = User.objects.get(id=id)
    
    if you in me.followings.all():
        me.followings.remove(you)
    else:
        me.followings.add(you)
    return redirect('accounts:detail', id)

movies/views.py
from django.shortcuts import render,redirect
from .models import Movie,Score
from .forms import ScoreForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
# Create your views here.
def list(request):
    movies = Movie.objects.all()
    return render(request, 'movies/list.html',{'movies':movies})
    
def detail(request,id):
    movie = Movie.objects.get(id=id)
    score_form = ScoreForm()
    return render(request,'movies/detail.html',{'movie':movie,'score_form':score_form})

@login_required
@require_POST
def score_create(request,id):
    score_form = ScoreForm(request.POST)
    if score_form.is_valid():
        score = score_form.save(commit=False)
        score.user = request.user
        score.movie = Movie.objects.get(id=id)
        score_form.save()
        return redirect("movies:detail",id)
        
@login_required
@require_POST
def score_delete(request, movie_id, score_id):
    score = Score.objects.get(id=score_id)
    if score.user == request.user:
        score.delete()
    return redirect("movies:detail", movie_id)
    
    
        

accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% block body %}
    {% if user.is_authenticated %}
        {% if user_info in user.followings.all %}
            <a href="{% url 'accounts:follow' user_info.id %}">팔로우 취소</a>
            {% else %}
            <a href="{% url 'accounts:follow' user_info.id %}">팔로우 하기</a>
        {% endif %}
    {% endif %}
    
    <h1>{{user_info.username}} 팔로잉: {{user_info.followings.count}}  팔로워:{{user_info.followers.count}}</h1>
    <h2>{{user_info.email}}</h2>
    <h2>댓글 리스트</h2>
    {% for score in user_info.score_set.all %}
        <h3>{{score.movie.title}} {{score.content}} {{score.value}}</h3>
    {% endfor %}
{% endblock %}

accounts/templates/accounts/forms.html
{% extends 'base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="!">
</form>
{% endblock %}

accounts/templates/accounts/list.html
{% extends 'base.html' %}

{% block body %}
    {% for user in users %}
        <a href="{% url 'accounts:detail' user.id %}"><h1>{{user.username}}</h1></a>
    {% endfor %}
{% endblock %}

movie_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <p>{{ user.username }}</p>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'accounts:signup' %}">회원가입</a>
        <a href="{% url 'accounts:login' %}">로그인</a>
    {% endif %}
    <hr> 
    {% block body %}
    {% endblock %}
</body>
</html>

movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block body %}
    <img src="{{movie.poster_url}}">
    <h1>{{movie.title}}</h1>
    <h2>{{movie.audience}}</h2>
    <h3>{{movie.description}}</h3>
    <h3>{{movie.genre}}</h3>
    {% if user.is_authenticated %}
    <form action="{% url 'movies:score_create' movie.id %}" method='post'>
        {% csrf_token %}
        {{score_form}}
        <input type="submit" value="Submit"/>
    </form>
    
    {% endif %}
    {% for score in movie.score_set.all %}
        <h2>{{score.content}} {{score.value}} {{score.user.username}} 
        {% if request.user == score.user %}
            <form action="{% url 'movies:score_delete' movie.id score.id %}" method='post'>
                {% csrf_token %}
                <input type="submit" value="삭제">
            </form>
            
             
        {% endif %}
        </h2>
        
    {% endfor %}
{% endblock %}

movies/templates/movies/list.html
{% extends 'base.html' %}
{% block body %}
    <h1>Movies List</h1>
    {% for movie in movies %}
        <a href="{% url 'movies:detail' movie.id %}"><img src="{{movie.poster_url}}"></a>
        <h2>{{movie.title}}</h2>
    {% endfor %}
{% endblock %}